#!/usr/bin/env python3
# SPDX-License-Identifier: EUPL-1.2
# role: library
#
# webgui/argolib.py — read-only Argo CD Application status via the in-cluster
# Kubernetes API (stdlib only). Powers the post-merge rollout check and the
# landing-page dashboard.
#
# Privilege: read-only on argoproj.io Applications in the argocd namespace, via a
# least-privilege ClusterRole bound to the portal ServiceAccount (deploy/rbac-argo.yaml).
# The pod must mount its SA token (automountServiceAccountToken: true).
#
# Writes: read-only. Requires: in-cluster SA token + CA (or KUBERNETES_API + SA_DIR
# overrides for tests).
"""Stdlib-only reader for Argo CD Application sync/health status."""

import json
import os
import ssl
import urllib.error
import urllib.request

_SA_DIR = os.environ.get("SA_DIR", "/var/run/secrets/kubernetes.io/serviceaccount")
_API = os.environ.get("KUBERNETES_API", "https://kubernetes.default.svc")
_ARGO_NS = os.environ.get("ARGO_NAMESPACE", "argocd")


class ArgoError(Exception):
    def __init__(self, status, detail):
        self.status = status
        self.detail = detail
        super().__init__(f"argo {status}: {detail}")


def _token():
    with open(f"{_SA_DIR}/token", encoding="utf-8") as fh:
        return fh.read().strip()


def _context():
    return ssl.create_default_context(cafile=f"{_SA_DIR}/ca.crt")


def _get(path):
    """GET a kube API path, return parsed JSON. Raises ArgoError (status carries
    the HTTP code; 0 for transport failures)."""
    req = urllib.request.Request(f"{_API}{path}", method="GET")
    req.add_header("Authorization", f"Bearer {_token()}")
    req.add_header("Accept", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=10, context=_context()) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        raise ArgoError(exc.code, f"HTTP {exc.code}") from None
    except urllib.error.URLError as exc:
        raise ArgoError(0, f"cannot reach kube API: {exc.reason}") from None


def _summary(app):
    """{sync, health, images} uit de Application-status.

    `images` komt uit `status.summary.images` — de images die Argo op de live
    resources van deze Application ziet. Dat is de kruiscontrole voor de
    image-downgrade-guard: git zegt wat er hoort te draaien, dit zegt wat Argo
    ziet. De volledige Application wordt in _get() al opgehaald, dus dit kost
    geen extra call en geen extra RBAC — de ClusterRole blijft read-only op
    argoproj.io Applications in argocd.

    Let op: dit is de PODSPEC-image, niet de versie die in het PVC geinstalleerd
    staat. Normaal lopen die gelijk; na een mislukte upgrade niet.
    """
    st = app.get("status", {})
    return {"sync": (st.get("sync") or {}).get("status"),
            "health": (st.get("health") or {}).get("status"),
            "images": list((st.get("summary") or {}).get("images") or [])}


def image_for_repository(images, repository):
    """De eerste image uit `images` waarvan het pad `repository` bevat, of None.

    Een tenant-Application draagt meerdere images (Nextcloud, de frontend, soms
    een sidecar), dus selecteren op positie is fout zodra de chart iets
    toevoegt. Matchen op het repository-pad is stabiel: `nextcloud`,
    `conductionnl/nextcloud-images`.
    """
    needle = str(repository or "").strip()
    if not needle:
        return None
    for image in images or []:
        # `<registry>/<repository>:<tag>` of `<repository>:<tag>`.
        path = str(image).rsplit(":", 1)[0]
        if path == needle or path.endswith(f"/{needle}"):
            return str(image)
    return None


def app_status(name):
    """{exists, sync, health} for one Application. 404 => exists False (not yet
    generated by the appset)."""
    try:
        app = _get(f"/apis/argoproj.io/v1alpha1/namespaces/{_ARGO_NS}/applications/{name}")
    except ArgoError as exc:
        if exc.status == 404:
            return {"exists": False, "sync": None, "health": None}
        raise
    return {"exists": True, **_summary(app)}


def list_apps(prefix="nc-"):
    """List Argo Applications whose name starts with `prefix` (the Nextcloud
    tenant apps), each as {name, tenant, sync, health}. Sorted by tenant."""
    data = _get(f"/apis/argoproj.io/v1alpha1/namespaces/{_ARGO_NS}/applications")
    out = []
    for app in data.get("items", []):
        name = app.get("metadata", {}).get("name", "")
        if not name.startswith(prefix):
            continue
        out.append({"name": name, "tenant": name[len(prefix):], **_summary(app)})
    return sorted(out, key=lambda a: a["tenant"])
