#!/usr/bin/env python3
# SPDX-License-Identifier: EUPL-1.2
# role: library
#
# webgui/argolib.py — read-only Argo CD Application status via the in-cluster
# Kubernetes API (stdlib only). Lets the portal show "PR merged -> Argo rolled it
# out (Synced/Healthy)" before handing off to provisioning.
#
# Privilege: read-only on argoproj.io Applications in the argocd namespace, via a
# least-privilege Role bound to the portal ServiceAccount (see deploy/rbac-argo.yaml).
# The pod must mount its SA token (automountServiceAccountToken: true).
#
# Writes: read-only. Requires: in-cluster SA token + CA (or KUBERNETES_API override
# + injected token/ca paths for tests).
"""Stdlib-only reader for Argo CD Application sync/health status."""

import json
import os
import ssl
import urllib.error
import urllib.request

_SA_DIR = os.environ.get("SA_DIR", "/var/run/secrets/kubernetes.io/serviceaccount")
_API = os.environ.get("KUBERNETES_API", "https://kubernetes.default.svc")
_ARGO_NS = os.environ.get("ARGO_NAMESPACE", "argocd")


class ArgoError(Exception):
    def __init__(self, status, detail):
        self.status = status
        self.detail = detail
        super().__init__(f"argo {status}: {detail}")


def _token():
    with open(f"{_SA_DIR}/token", encoding="utf-8") as fh:
        return fh.read().strip()


def _context():
    return ssl.create_default_context(cafile=f"{_SA_DIR}/ca.crt")


def app_status(name):
    """Return {exists, sync, health} for Argo Application <name> in the argocd ns.
    A missing Application (404) => exists False (not yet generated by the appset)."""
    path = f"/apis/argoproj.io/v1alpha1/namespaces/{_ARGO_NS}/applications/{name}"
    req = urllib.request.Request(f"{_API}{path}", method="GET")
    req.add_header("Authorization", f"Bearer {_token()}")
    req.add_header("Accept", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=10, context=_context()) as resp:
            app = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return {"exists": False, "sync": None, "health": None}
        raise ArgoError(exc.code, f"HTTP {exc.code}") from None
    except urllib.error.URLError as exc:
        raise ArgoError(0, f"cannot reach kube API: {exc.reason}") from None
    st = app.get("status", {})
    return {
        "exists": True,
        "sync": (st.get("sync") or {}).get("status"),
        "health": (st.get("health") or {}).get("status"),
    }
